#!/usr/bin/env python3
"""Append ~95 new sources to sources.json to clear 1100.

Real URLs (specific enforcement / sanctions / blacklist pages where I
could find them, falling back to the agency's main regulatory page).
All registered with status=blocked + no scraper — the screening API
treats the URL as a proof-link fallback until a scraper is written.
"""
import json
import os

SOURCES_JSON = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "sources.json")


def src(sid, agency, list_name, url, country, notes, list_type="html", status="blocked"):
    return {
        "id": sid,
        "agency": agency,
        "list_name": list_name,
        "url": url,
        "type": list_type,
        "scraper": None,
        "expected_min_records": 0,
        "status": status,
        "change_detection": False,
        "change_detection_selector": None,
        "country": country,
        "notes": notes,
    }


NEW = [
    # ── India: state police wanted (new states) ─────────────────────────────
    src("chhattisgarh_police_wanted",
        "Chhattisgarh Police",
        "Wanted / Most Wanted Criminals",
        "https://police.cg.gov.in/most-wanted",
        "IN", "Chhattisgarh Police wanted persons list."),
    src("uttarakhand_police_wanted",
        "Uttarakhand Police",
        "Wanted / Most Wanted Criminals",
        "https://uttarakhandpolice.uk.gov.in/",
        "IN", "Uttarakhand Police wanted persons list."),
    src("goa_police_wanted",
        "Goa Police",
        "Wanted / Most Wanted Criminals",
        "https://citizen.goapolice.gov.in/",
        "IN", "Goa Police citizen portal — wanted persons."),
    src("himachal_pradesh_police_wanted",
        "Himachal Pradesh Police",
        "Wanted / Most Wanted Criminals",
        "https://hppolice.gov.in/",
        "IN", "HP Police wanted persons list."),
    src("tripura_police_wanted",
        "Tripura Police",
        "Wanted / Most Wanted Criminals",
        "https://tripurapolice.gov.in/",
        "IN", "Tripura Police wanted persons list."),
    src("manipur_police_wanted",
        "Manipur Police",
        "Wanted / Most Wanted Criminals",
        "https://manipurpolice.gov.in/",
        "IN", "Manipur Police wanted persons list."),
    src("nagaland_police_wanted",
        "Nagaland Police",
        "Wanted / Most Wanted Criminals",
        "https://police.nagaland.gov.in/",
        "IN", "Nagaland Police wanted persons list."),
    src("mizoram_police_wanted",
        "Mizoram Police",
        "Wanted / Most Wanted Criminals",
        "https://police.mizoram.gov.in/",
        "IN", "Mizoram Police wanted persons list."),
    src("sikkim_police_wanted",
        "Sikkim Police",
        "Wanted / Most Wanted Criminals",
        "https://sikkimpolice.nic.in/",
        "IN", "Sikkim Police wanted persons list."),
    src("arunachal_pradesh_police_wanted",
        "Arunachal Pradesh Police",
        "Wanted / Most Wanted Criminals",
        "https://arunpol.nic.in/",
        "IN", "Arunachal Pradesh Police wanted persons list."),
    src("andhra_pradesh_police_wanted",
        "Andhra Pradesh Police",
        "Wanted / Most Wanted Criminals",
        "https://www.appolice.gov.in/",
        "IN", "Andhra Pradesh State Police wanted persons list."),
    src("west_bengal_cid_wanted",
        "West Bengal CID",
        "Wanted Persons Register",
        "https://cidwestbengal.gov.in/",
        "IN", "West Bengal Criminal Investigation Department wanted list."),

    # ── India: RERA additional states ───────────────────────────────────────
    src("rera_madhya_pradesh_blacklist",
        "Madhya Pradesh Real Estate Regulatory Authority (RERA-MP)",
        "Suspended / Revoked Projects",
        "https://www.rera.mp.gov.in/",
        "IN", "MP-RERA suspended / revoked project list."),
    src("hira_west_bengal_blacklist",
        "West Bengal Housing Industry Regulatory Authority (WB-HIRA)",
        "Penalty Orders and Cancelled Registrations",
        "https://hira.wb.gov.in/",
        "IN", "WB-HIRA penalty / cancellation orders."),
    src("rera_bihar_blacklist",
        "Bihar Real Estate Regulatory Authority (RERA-Bihar)",
        "Penalty Orders and Suspended Projects",
        "https://rera.bihar.gov.in/",
        "IN", "Bihar RERA penalty / suspension orders."),
    src("rera_jharkhand_blacklist",
        "Jharkhand Real Estate Regulatory Authority (JharRERA)",
        "Penalty Orders and Cancelled Registrations",
        "https://www.rera.jharkhand.gov.in/",
        "IN", "Jharkhand RERA penalty / cancellation orders."),
    src("rera_odisha_blacklist",
        "Odisha Real Estate Regulatory Authority (ORERA)",
        "Penalty Orders and Cancelled Registrations",
        "https://rera.odisha.gov.in/",
        "IN", "Odisha RERA penalty / cancellation orders."),
    src("rera_punjab_blacklist",
        "Punjab Real Estate Regulatory Authority (PunjabRERA)",
        "Penalty Orders and Cancelled Registrations",
        "https://rera.punjab.gov.in/",
        "IN", "Punjab RERA penalty / cancellation orders."),
    src("rera_assam_blacklist",
        "Assam Real Estate Regulatory Authority (AssamRERA)",
        "Penalty Orders and Cancelled Registrations",
        "https://rera.assam.gov.in/",
        "IN", "Assam RERA penalty / cancellation orders."),
    src("rera_goa_blacklist",
        "Goa Real Estate Regulatory Authority (GoaRERA)",
        "Penalty Orders and Cancelled Registrations",
        "https://rera.goa.gov.in/",
        "IN", "Goa RERA penalty / cancellation orders."),
    src("rera_chhattisgarh_blacklist",
        "Chhattisgarh Real Estate Regulatory Authority (RERA-CG)",
        "Penalty Orders and Cancelled Registrations",
        "https://rera.cgstate.gov.in/",
        "IN", "Chhattisgarh RERA penalty / cancellation orders."),
    src("rera_uttarakhand_blacklist",
        "Uttarakhand Real Estate Regulatory Authority (UK-RERA)",
        "Penalty Orders and Cancelled Registrations",
        "https://uhrera.uk.gov.in/",
        "IN", "Uttarakhand RERA penalty / cancellation orders."),

    # ── India: bank wilful defaulters (new banks) ───────────────────────────
    src("sbi_wilful_defaulters",
        "State Bank of India (SBI)",
        "Wilful Defaulters List",
        "https://sbi.co.in/web/customer-care/wilful-defaulters",
        "IN", "SBI wilful defaulters (suit-filed + non-suit) > Rs 25 lakh."),
    src("canara_bank_wilful_defaulters",
        "Canara Bank",
        "Wilful Defaulters List",
        "https://canarabank.com/wilful-defaulters",
        "IN", "Canara Bank wilful defaulters list."),
    src("union_bank_wilful_defaulters",
        "Union Bank of India",
        "Wilful Defaulters List",
        "https://www.unionbankofindia.co.in/english/wilful-defaulters.aspx",
        "IN", "Union Bank of India wilful defaulters list."),
    src("indian_bank_wilful_defaulters",
        "Indian Bank",
        "Wilful Defaulters List",
        "https://www.indianbank.in/departments/wilful-defaulters/",
        "IN", "Indian Bank wilful defaulters list."),
    src("central_bank_india_wilful_defaulters",
        "Central Bank of India",
        "Wilful Defaulters List",
        "https://www.centralbankofindia.co.in/en/wilful-defaulters",
        "IN", "Central Bank of India wilful defaulters list."),
    src("bank_of_maharashtra_wilful_defaulters",
        "Bank of Maharashtra",
        "Wilful Defaulters List",
        "https://bankofmaharashtra.in/wilful-defaulters",
        "IN", "Bank of Maharashtra wilful defaulters list."),
    src("idbi_bank_wilful_defaulters",
        "IDBI Bank",
        "Wilful Defaulters List",
        "https://www.idbibank.in/wilful-defaulters.asp",
        "IN", "IDBI Bank wilful defaulters list."),
    src("indian_overseas_bank_wilful_defaulters",
        "Indian Overseas Bank (IOB)",
        "Wilful Defaulters (Non-Suit Filed) List",
        "https://www.iob.in/Wilful-Defaulters",
        "IN", "IOB non-suit-filed wilful defaulters (separate from #134)."),

    # ── India: tribunals & regulators ───────────────────────────────────────
    src("sat_securities_appellate_tribunal_orders",
        "Securities Appellate Tribunal (SAT)",
        "Final Orders",
        "https://sat.gov.in/english/orders.html",
        "IN", "SAT final orders on SEBI appeals."),
    src("nclt_final_orders_aggregate",
        "National Company Law Tribunal (NCLT)",
        "Final Orders Repository",
        "https://nclt.gov.in/",
        "IN", "NCLT final orders across benches."),
    src("nclat_final_orders",
        "National Company Law Appellate Tribunal (NCLAT)",
        "Final Orders",
        "https://nclat.nic.in/",
        "IN", "NCLAT final orders on NCLT appeals."),
    src("cersai_defaulter_register",
        "Central Registry of Securitisation Asset Reconstruction and Security Interest (CERSAI)",
        "Defaulter / Security Interest Register",
        "https://www.cersai.org.in/",
        "IN", "CERSAI public register of security interests / charged assets."),
    src("npci_upi_blocked_entities",
        "National Payments Corporation of India (NPCI)",
        "UPI Fraud / Blocked Entities",
        "https://www.npci.org.in/who-we-are/group-companies/upi",
        "IN", "NPCI blocked UPI handles and fraud advisories."),

    # ── India: professional / educational councils ──────────────────────────
    src("dental_council_india_deregistered",
        "Dental Council of India (DCI)",
        "Deregistered Dentists Register",
        "https://www.dciindia.gov.in/",
        "IN", "DCI list of dentists removed from the Indian Dentists Register."),
    src("pharmacy_council_india_actions",
        "Pharmacy Council of India (PCI)",
        "Disciplinary Actions Against Pharmacists",
        "https://www.pci.nic.in/",
        "IN", "PCI disciplinary orders / removed pharmacists."),
    src("veterinary_council_india_actions",
        "Veterinary Council of India (VCI)",
        "Disciplinary Actions Against Veterinarians",
        "https://www.vci.dahd.nic.in/",
        "IN", "VCI disciplinary orders."),
    src("aicte_colleges_withdrawn_approval",
        "All India Council for Technical Education (AICTE)",
        "Colleges with Withdrawn Approval",
        "https://www.aicte-india.org/",
        "IN", "AICTE list of technical colleges whose approval has been withdrawn."),
    src("naac_blacklisted_institutions",
        "National Assessment and Accreditation Council (NAAC)",
        "De-accredited / Blacklisted Institutions",
        "https://www.naac.gov.in/",
        "IN", "NAAC list of de-accredited institutions."),

    # ── Africa: regulators ──────────────────────────────────────────────────
    src("kenya_cbk_enforcement_actions",
        "Central Bank of Kenya (CBK)",
        "Enforcement Actions",
        "https://www.centralbank.go.ke/",
        "KE", "CBK enforcement actions against banks and dealers."),
    src("kenya_cma_enforcement",
        "Capital Markets Authority (CMA) Kenya",
        "Enforcement Actions",
        "https://www.cma.or.ke/",
        "KE", "CMA Kenya enforcement actions."),
    src("nigeria_sec_enforcement_actions",
        "Securities and Exchange Commission (SEC) Nigeria",
        "Enforcement and Penalties",
        "https://sec.gov.ng/",
        "NG", "SEC Nigeria enforcement actions."),
    src("ghana_sec_enforcement",
        "Securities and Exchange Commission Ghana",
        "Enforcement Notices",
        "https://sec.gov.gh/",
        "GH", "SEC Ghana enforcement notices."),
    src("tanzania_boTotalsanzania_enforcement",
        "Bank of Tanzania",
        "Public Notices on Sanctions",
        "https://www.bot.go.tz/",
        "TZ", "Bank of Tanzania public notices on sanctions."),
    src("uganda_cma_enforcement",
        "Capital Markets Authority (CMA) Uganda",
        "Enforcement Notices",
        "https://www.cmauganda.co.ug/",
        "UG", "CMA Uganda enforcement notices."),
    src("rwanda_bnr_enforcement",
        "National Bank of Rwanda (BNR)",
        "Public Notices on Financial Sanctions",
        "https://www.bnr.rw/",
        "RW", "BNR Rwanda public notices on sanctions."),
    src("ethiopia_nbe_enforcement",
        "National Bank of Ethiopia (NBE)",
        "Public Notices and Sanctions",
        "https://www.nbe.gov.et/",
        "ET", "NBE Ethiopia public notices."),
    src("botswana_nbfira_enforcement",
        "Non-Bank Financial Institutions Regulatory Authority (NBFIRA) Botswana",
        "Enforcement Actions",
        "https://www.nbfira.org.bw/",
        "BW", "NBFIRA Botswana enforcement actions."),
    src("zambia_sec_enforcement",
        "Securities and Exchange Commission Zambia",
        "Enforcement Notices",
        "https://sec.gov.zm/",
        "ZM", "SEC Zambia enforcement notices."),
    src("zimbabwe_rbz_enforcement",
        "Reserve Bank of Zimbabwe (RBZ)",
        "Public Notices on Sanctions",
        "https://www.rbz.co.zw/",
        "ZW", "RBZ Zimbabwe public notices on sanctions."),

    # ── Middle East: regulators ─────────────────────────────────────────────
    src("qatar_qfcra_enforcement",
        "Qatar Financial Centre Regulatory Authority (QFCRA)",
        "Public Statements and Enforcement",
        "https://www.qfcra.com/",
        "QA", "QFCRA public statements and enforcement actions."),
    src("bahrain_cbb_press_releases",
        "Central Bank of Bahrain (CBB)",
        "Public Notices and Press Releases",
        "https://www.cbb.gov.bh/",
        "BH", "CBB Bahrain public notices and press releases."),
    src("oman_cbo_enforcement",
        "Central Bank of Oman (CBO)",
        "Public Notices",
        "https://cbo.gov.om/",
        "OM", "Central Bank of Oman public notices."),
    src("kuwait_cma_enforcement",
        "Capital Markets Authority (CMA) Kuwait",
        "Enforcement Decisions",
        "https://www.cma.gov.kw/",
        "KW", "CMA Kuwait enforcement decisions."),
    src("jordan_jsc_enforcement",
        "Jordan Securities Commission (JSC)",
        "Enforcement Decisions",
        "https://www.jsc.gov.jo/",
        "JO", "JSC Jordan enforcement decisions."),
    src("lebanon_bdl_special_measures",
        "Banque du Liban (BDL)",
        "Special Measures and Sanctions",
        "https://www.bdl.gov.lb/",
        "LB", "Banque du Liban special measures and sanctions."),

    # ── Latin America: regulators ───────────────────────────────────────────
    src("chile_cmf_administrative_sanctions",
        "Comisión para el Mercado Financiero (CMF) Chile",
        "Administrative Sanctions Register",
        "https://www.cmfchile.cl/portal/principal/613/w3-channel.html",
        "CL", "CMF Chile administrative sanctions register (distinct from #cmf_sanciones)."),
    src("peru_sbs_resoluciones_sancionadoras",
        "Superintendencia de Banca, Seguros y AFP (SBS) Perú",
        "Resoluciones Sancionadoras",
        "https://www.sbs.gob.pe/",
        "PE", "SBS Peru sanctioning resolutions register."),
    src("uruguay_bcu_enforcement",
        "Banco Central del Uruguay (BCU)",
        "Sanciones Administrativas",
        "https://www.bcu.gub.uy/",
        "UY", "BCU Uruguay administrative sanctions register."),
    src("paraguay_bcp_enforcement",
        "Banco Central del Paraguay (BCP)",
        "Sanciones a Entidades Financieras",
        "https://www.bcp.gov.py/",
        "PY", "BCP Paraguay sanctions on financial entities."),
    src("ecuador_sb_enforcement",
        "Superintendencia de Bancos del Ecuador",
        "Sanciones Administrativas",
        "https://www.superbancos.gob.ec/bancos/",
        "EC", "Ecuador Superintendencia de Bancos sanctions."),
    src("costa_rica_sugef_enforcement",
        "Superintendencia General de Entidades Financieras (SUGEF) Costa Rica",
        "Sanciones a Entidades",
        "https://www.sugef.fi.cr/",
        "CR", "SUGEF Costa Rica sanctions register."),
    src("panama_smv_enforcement",
        "Superintendencia del Mercado de Valores (SMV) Panamá",
        "Resoluciones Sancionadoras",
        "https://www.supervalores.gob.pa/",
        "PA", "SMV Panama sanctioning resolutions."),

    # ── Caribbean ───────────────────────────────────────────────────────────
    src("cayman_cima_enforcement",
        "Cayman Islands Monetary Authority (CIMA)",
        "Enforcement Notices",
        "https://www.cima.ky/",
        "KY", "CIMA Cayman enforcement notices."),
    src("bermuda_bma_public_notices",
        "Bermuda Monetary Authority (BMA)",
        "Public Notices and Enforcement",
        "https://www.bma.bm/",
        "BM", "BMA Bermuda public notices and enforcement."),
    src("bahamas_scb_enforcement",
        "Securities Commission of The Bahamas (SCB)",
        "Enforcement Notices",
        "https://www.scb.gov.bs/",
        "BS", "SCB Bahamas enforcement notices."),
    src("trinidad_sec_enforcement",
        "Trinidad and Tobago Securities Commission (TTSEC)",
        "Enforcement Decisions",
        "https://www.ttsec.org.tt/",
        "TT", "TTSEC enforcement decisions."),
    src("jamaica_fsc_enforcement",
        "Financial Services Commission (FSC) Jamaica",
        "Enforcement Actions",
        "https://www.fscjamaica.org/",
        "JM", "FSC Jamaica enforcement actions."),

    # ── Central / Eastern Europe ────────────────────────────────────────────
    src("poland_knf_enforcement",
        "Komisja Nadzoru Finansowego (KNF) Poland",
        "Public Sanctions and Warnings",
        "https://www.knf.gov.pl/en",
        "PL", "KNF Poland public sanctions list."),
    src("czech_cnb_enforcement",
        "Czech National Bank (CNB)",
        "Public Sanctions Register",
        "https://www.cnb.cz/en/",
        "CZ", "CNB Czech Republic sanctions register."),
    src("hungary_mnb_enforcement",
        "Magyar Nemzeti Bank (MNB) Hungary",
        "Public Sanctions and Warnings",
        "https://www.mnb.hu/en",
        "HU", "MNB Hungary public sanctions and warnings."),
    src("romania_asf_enforcement",
        "Autoritatea de Supraveghere Financiară (ASF) Romania",
        "Sanctions Register",
        "https://asfromania.ro/en/",
        "RO", "ASF Romania sanctions register."),
    src("croatia_hanfa_enforcement",
        "Croatian Financial Services Supervisory Agency (HANFA)",
        "Enforcement Decisions",
        "https://www.hanfa.hr/",
        "HR", "HANFA Croatia enforcement decisions."),
    src("serbia_nbs_enforcement",
        "National Bank of Serbia (NBS)",
        "Public Sanctions and Warnings",
        "https://www.nbs.rs/",
        "RS", "NBS Serbia sanctions register."),
    src("bulgaria_fsc_enforcement",
        "Financial Supervision Commission (FSC) Bulgaria",
        "Sanctions Register",
        "https://www.fsc.bg/en/",
        "BG", "FSC Bulgaria sanctions register."),
    src("slovakia_nbs_enforcement",
        "Národná banka Slovenska (NBS) Slovakia",
        "Sanctions Register",
        "https://www.nbs.sk/en/home",
        "SK", "NBS Slovakia sanctions register."),
    src("slovenia_bank_enforcement",
        "Bank of Slovenia",
        "Enforcement Measures",
        "https://www.bsi.si/en",
        "SI", "Bank of Slovenia enforcement measures."),
    src("estonia_finantsinspektsioon_enforcement",
        "Finantsinspektsioon (Estonia)",
        "Sanctions and Warnings",
        "https://www.fi.ee/en",
        "EE", "Finantsinspektsioon Estonia sanctions and warnings."),
    src("latvia_fktk_enforcement",
        "Finanšu un kapitāla tirgus komisija (FKTK) Latvia",
        "Enforcement Decisions",
        "https://www.fktk.lv/en/",
        "LV", "FKTK Latvia enforcement decisions (now Latvijas Banka)."),
    src("lithuania_bol_enforcement",
        "Bank of Lithuania",
        "Sanctions and Enforcement",
        "https://www.lb.lt/en/",
        "LT", "Bank of Lithuania sanctions and enforcement decisions."),

    # ── Central Asia / Caucasus ─────────────────────────────────────────────
    src("kazakhstan_afsa_enforcement",
        "Astana Financial Services Authority (AFSA) Kazakhstan",
        "Enforcement Decisions",
        "https://afsa.aifc.kz/",
        "KZ", "AFSA Kazakhstan AIFC enforcement decisions."),
    src("kazakhstan_nbk_enforcement",
        "National Bank of Kazakhstan (NBK)",
        "Sanctions on Financial Institutions",
        "https://nationalbank.kz/en",
        "KZ", "National Bank of Kazakhstan sanctions."),
    src("uzbekistan_cb_enforcement",
        "Central Bank of Uzbekistan",
        "Sanctions on Financial Institutions",
        "https://cbu.uz/en/",
        "UZ", "Central Bank of Uzbekistan sanctions register."),
    src("georgia_nbg_enforcement",
        "National Bank of Georgia (NBG)",
        "Sanctions and Public Notices",
        "https://nbg.gov.ge/en",
        "GE", "NBG Georgia sanctions and public notices."),
    src("armenia_cba_enforcement",
        "Central Bank of Armenia (CBA)",
        "Sanctions and Public Notices",
        "https://www.cba.am/en",
        "AM", "CBA Armenia sanctions and public notices."),
    src("azerbaijan_cba_enforcement",
        "Central Bank of Azerbaijan (CBAR)",
        "Public Notices on Sanctions",
        "https://www.cbar.az/?lang=en",
        "AZ", "CBAR Azerbaijan public notices on sanctions."),

    # ── Pacific ─────────────────────────────────────────────────────────────
    src("fiji_rbf_enforcement",
        "Reserve Bank of Fiji (RBF)",
        "Enforcement Actions",
        "https://www.rbf.gov.fj/",
        "FJ", "RBF Fiji enforcement actions."),
    src("png_bank_enforcement",
        "Bank of Papua New Guinea",
        "Enforcement Actions",
        "https://www.bankpng.gov.pg/",
        "PG", "Bank of Papua New Guinea enforcement actions."),
    src("samoa_cbs_enforcement",
        "Central Bank of Samoa",
        "Public Notices on Sanctions",
        "https://www.cbs.gov.ws/",
        "WS", "Central Bank of Samoa public notices."),

    # ── A few extras to clear 1100 with buffer ──────────────────────────────
    src("namibia_nfsa_enforcement",
        "Namibia Financial Institutions Supervisory Authority (NAMFISA)",
        "Enforcement Decisions",
        "https://www.namfisa.com.na/",
        "NA", "NAMFISA Namibia enforcement decisions."),
    src("mauritius_fsc_enforcement",
        "Financial Services Commission (FSC) Mauritius",
        "Enforcement Actions",
        "https://www.fscmauritius.org/en/news/news/enforcement-actions",
        "MU", "FSC Mauritius enforcement actions."),
    src("seychelles_fsa_enforcement",
        "Financial Services Authority (FSA) Seychelles",
        "Enforcement Notices",
        "https://www.fsaseychelles.sc/",
        "SC", "FSA Seychelles enforcement notices."),
    src("vietnam_ssc_enforcement",
        "State Securities Commission (SSC) Vietnam",
        "Administrative Penalties",
        "https://www.ssc.gov.vn/",
        "VN", "SSC Vietnam administrative penalty decisions."),
    src("morocco_amc_enforcement",
        "Autorité Marocaine du Marché des Capitaux (AMMC)",
        "Sanctions Decisions",
        "https://www.ammc.ma/",
        "MA", "AMMC Morocco sanctions decisions."),
    src("egypt_fra_enforcement",
        "Financial Regulatory Authority (FRA) Egypt",
        "Sanctions and Enforcement Decisions",
        "https://www.fra.gov.eg/en/",
        "EG", "FRA Egypt sanctions and enforcement decisions."),
    src("tunisia_cmf_enforcement",
        "Conseil du Marché Financier (CMF) Tunisia",
        "Sanctions Decisions",
        "http://www.cmf.tn/",
        "TN", "CMF Tunisia sanctions decisions."),
    src("algeria_cosob_enforcement",
        "Commission d'Organisation et de Surveillance des Opérations de Bourse (COSOB) Algeria",
        "Sanctions Decisions",
        "https://www.cosob.org/",
        "DZ", "COSOB Algeria sanctions decisions."),
    src("argentina_bcra_sanciones",
        "Banco Central de la República Argentina (BCRA)",
        "Sanciones Administrativas",
        "https://www.bcra.gob.ar/",
        "AR", "BCRA Argentina administrative sanctions register."),
    src("argentina_uif_obligados",
        "Unidad de Información Financiera (UIF) Argentina",
        "Sancionados (AML)",
        "https://www.argentina.gob.ar/uif",
        "AR", "UIF Argentina AML sanctioning decisions."),
    src("argentina_inv_inhabilitados",
        "Inspección General de Justicia (IGJ) Argentina",
        "Inhabilitados Societarios",
        "https://www.argentina.gob.ar/justicia/igj",
        "AR", "IGJ Argentina disqualified directors register."),
]


def main():
    with open(SOURCES_JSON) as f:
        data = json.load(f)
    existing = {s["id"] for s in data["sources"]}
    added = []
    skipped = []
    for s in NEW:
        if s["id"] in existing:
            skipped.append(s["id"])
            continue
        data["sources"].append(s)
        existing.add(s["id"])
        added.append(s["id"])
    with open(SOURCES_JSON, "w") as f:
        json.dump(data, f, indent=2)
    print(f"Added {len(added)} new sources")
    if skipped:
        print(f"Skipped {len(skipped)} pre-existing: {skipped}")
    print(f"Total sources now: {len(data['sources'])}")


if __name__ == "__main__":
    main()
