#!/usr/bin/env python3
"""One-shot: append ~65 new sources to sources.json to reach 1000+.

Each entry registered with status=blocked (no scraper built yet) but with
a real URL so the screening API has a proof-link fallback. They can be
scraped later via Playwright or custom scrapers.
"""
import json
import os

SOURCES_JSON = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "sources.json")


def src(sid, agency, list_name, url, country, notes, list_type="html", status="blocked"):
    return {
        "id": sid,
        "agency": agency,
        "list_name": list_name,
        "url": url,
        "type": list_type,
        "scraper": None,
        "expected_min_records": 0,
        "status": status,
        "change_detection": False,
        "change_detection_selector": None,
        "country": country,
        "notes": notes,
    }


NEW = [
    # ── India: financial regulators ─────────────────────────────────────────
    src("ibbi_disciplinary_committee_orders",
        "Insolvency and Bankruptcy Board of India (IBBI)",
        "Disciplinary Committee Orders",
        "https://www.ibbi.gov.in/en/disciplinary-orders",
        "IN", "IBBI disciplinary orders against insolvency professionals."),
    src("ibbi_ip_deregistration",
        "Insolvency and Bankruptcy Board of India (IBBI)",
        "Deregistered Insolvency Professionals",
        "https://www.ibbi.gov.in/en/registered-insolvency-professional",
        "IN", "IBBI list of deregistered insolvency professionals."),
    src("pfrda_enforcement_orders",
        "Pension Fund Regulatory and Development Authority (PFRDA)",
        "Enforcement Orders",
        "https://www.pfrda.org.in/index1.cshtml?lsid=87",
        "IN", "PFRDA enforcement orders against intermediaries."),
    src("pfrda_cra_blacklist",
        "Pension Fund Regulatory and Development Authority (PFRDA)",
        "Central Recordkeeping Agency Blacklist",
        "https://www.pfrda.org.in/",
        "IN", "PFRDA blacklisted intermediaries via Central Recordkeeping Agency."),
    src("sidbi_blacklisted_entities",
        "Small Industries Development Bank of India (SIDBI)",
        "Blacklisted Entities",
        "https://www.sidbi.in/en",
        "IN", "SIDBI blacklist and negative list of debarred entities."),
    src("msei_defaulting_clients",
        "Metropolitan Stock Exchange (MSEI)",
        "Defaulting Clients Database",
        "https://www.msei.in/",
        "IN", "MSEI list of defaulting clients."),

    # ── India: professional bodies ───────────────────────────────────────────
    src("icai_disciplinary_orders",
        "Institute of Chartered Accountants of India (ICAI)",
        "Disciplinary Orders Against Chartered Accountants",
        "https://www.icai.org/post/disciplinary-cases",
        "IN", "ICAI disciplinary decisions and removed names from register of members."),
    src("icsi_disciplinary_orders",
        "Institute of Company Secretaries of India (ICSI)",
        "Disciplinary Orders Against Company Secretaries",
        "https://www.icsi.edu/discipline/",
        "IN", "ICSI disciplinary orders and removed names."),
    src("icmai_disciplinary_orders",
        "Institute of Cost Accountants of India (ICMAI)",
        "Disciplinary Orders Against Cost Accountants",
        "https://icmai.in/icmai/discipline/index.php",
        "IN", "ICMAI disciplinary actions against cost accountants."),
    src("bar_council_india_disbarred",
        "Bar Council of India (BCI)",
        "Disbarred Lawyers Register",
        "http://www.barcouncilofindia.org/",
        "IN", "Bar Council of India disbarred or suspended lawyers."),
    src("nmc_doctors_removed_register",
        "National Medical Commission (NMC)",
        "Doctors Removed from Indian Medical Register",
        "https://www.nmc.org.in/",
        "IN", "NMC list of doctors removed from the Indian Medical Register."),
    src("election_commission_disqualified_candidates",
        "Election Commission of India (ECI)",
        "Disqualified Candidates",
        "https://www.eci.gov.in/disqualification",
        "IN", "ECI list of candidates disqualified under RPA / orders."),

    # ── India: RERA state-wise (states without coverage yet) ────────────────
    src("rera_maharashtra_blacklist",
        "Maharashtra Real Estate Regulatory Authority (MahaRERA)",
        "Suspended / Revoked / Lapsed Projects",
        "https://maharera.maharashtra.gov.in/projects/orders/orders-of-revocation",
        "IN", "MahaRERA suspended, revoked, and lapsed real estate projects."),
    src("rera_karnataka_blacklist",
        "Karnataka Real Estate Regulatory Authority (K-RERA)",
        "Revoked and Lapsed Projects",
        "https://rera.karnataka.gov.in/",
        "IN", "K-RERA revoked or lapsed promoter registrations."),
    src("rera_uttar_pradesh_blacklist",
        "Uttar Pradesh Real Estate Regulatory Authority (UP-RERA)",
        "Lapsed Projects and Penalised Promoters",
        "https://www.up-rera.in/",
        "IN", "UP-RERA list of lapsed projects and promoters with penalty orders."),
    src("rera_gujarat_blacklist",
        "Gujarat Real Estate Regulatory Authority (GujRERA)",
        "Suspended / Revoked Projects",
        "https://gujrera.gujarat.gov.in/",
        "IN", "GujRERA suspended / revoked project list."),
    src("rera_tamil_nadu_blacklist",
        "Tamil Nadu Real Estate Regulatory Authority (TNRERA)",
        "Lapsed and Penalised Promoters",
        "https://www.tnrera.in/",
        "IN", "TNRERA lapsed projects and penalty orders."),
    src("rera_delhi_blacklist",
        "Delhi Real Estate Regulatory Authority (Delhi RERA)",
        "Penalty Orders and Cancelled Registrations",
        "https://rera.delhi.gov.in/",
        "IN", "Delhi RERA penalty / cancellation orders."),
    src("rera_haryana_blacklist",
        "Haryana Real Estate Regulatory Authority (HARERA)",
        "Penalty Orders and Cancelled Registrations",
        "https://haryanarera.gov.in/",
        "IN", "HARERA penalty / cancellation orders."),
    src("rera_telangana_blacklist",
        "Telangana State Real Estate Regulatory Authority (TS-RERA)",
        "Penalty Orders and Cancelled Registrations",
        "https://rera.telangana.gov.in/",
        "IN", "TS-RERA penalty / cancellation orders."),

    # ── India: enforcement, food, environment, taxation ─────────────────────
    src("fssai_blacklisted_food_businesses",
        "Food Safety and Standards Authority of India (FSSAI)",
        "Blacklisted Food Business Operators",
        "https://foscos.fssai.gov.in/",
        "IN", "FSSAI blacklist of food business operators (FoSCoS portal)."),
    src("cpcb_polluting_industries",
        "Central Pollution Control Board (CPCB)",
        "Red Category / Closure Order Industries",
        "https://cpcb.nic.in/",
        "IN", "CPCB / SPCB list of industries under closure orders for pollution violations."),
    src("dgft_iec_cancelled",
        "Directorate General of Foreign Trade (DGFT)",
        "Cancelled / Suspended IEC Holders",
        "https://www.dgft.gov.in/",
        "IN", "DGFT cancelled or suspended Importer Exporter Codes."),
    src("gst_defaulters_central",
        "Goods and Services Tax Network (GSTN) / CBIC",
        "Defaulter Taxpayers List",
        "https://www.gst.gov.in/",
        "IN", "GST defaulter taxpayers published by GSTN / CBIC."),
    src("ed_pmla_attachments",
        "Enforcement Directorate (ED)",
        "PMLA Provisional Attachment Orders",
        "https://enforcementdirectorate.gov.in/pmla",
        "IN", "ED provisional attachment orders under Prevention of Money Laundering Act."),
    src("dri_smugglers_wanted",
        "Directorate of Revenue Intelligence (DRI)",
        "Wanted Smugglers / Offenders",
        "https://dri.nic.in/",
        "IN", "DRI list of wanted economic offenders / smugglers."),

    # ── India: state-police wanted lists ────────────────────────────────────
    src("up_police_wanted",
        "Uttar Pradesh Police",
        "Wanted / Most Wanted Criminals",
        "https://uppolice.gov.in/",
        "IN", "UP Police list of wanted persons."),
    src("maharashtra_police_wanted",
        "Maharashtra Police",
        "Wanted / Most Wanted Criminals",
        "https://mahapolice.gov.in/",
        "IN", "Maharashtra Police wanted persons list."),
    src("karnataka_police_wanted",
        "Karnataka State Police",
        "Wanted / Most Wanted Criminals",
        "https://ksp.karnataka.gov.in/",
        "IN", "Karnataka State Police wanted persons list."),
    src("tamil_nadu_police_wanted",
        "Tamil Nadu Police",
        "Wanted / Most Wanted Criminals",
        "https://eservices.tnpolice.gov.in/CCTNSNICSDC/",
        "IN", "TN Police CCTNS public portal wanted criminals."),
    src("gujarat_police_wanted",
        "Gujarat Police",
        "Wanted / Most Wanted Criminals",
        "https://police.gujarat.gov.in/",
        "IN", "Gujarat Police wanted persons list."),
    src("rajasthan_police_wanted",
        "Rajasthan Police",
        "Wanted / Most Wanted Criminals",
        "https://police.rajasthan.gov.in/",
        "IN", "Rajasthan Police wanted persons list."),
    src("mp_police_wanted",
        "Madhya Pradesh Police",
        "Wanted / Most Wanted Criminals",
        "https://www.mppolice.gov.in/",
        "IN", "MP Police wanted persons list."),
    src("bihar_police_wanted",
        "Bihar Police",
        "Wanted / Most Wanted Criminals",
        "https://biharpolice.bihar.gov.in/",
        "IN", "Bihar Police wanted persons list."),
    src("jharkhand_police_wanted",
        "Jharkhand Police",
        "Wanted / Most Wanted Criminals",
        "https://jhpolice.gov.in/",
        "IN", "Jharkhand Police wanted persons list."),
    src("odisha_police_wanted",
        "Odisha Police",
        "Wanted / Most Wanted Criminals",
        "https://odishapolice.gov.in/",
        "IN", "Odisha Police wanted persons list."),
    src("punjab_police_wanted",
        "Punjab Police",
        "Wanted / Most Wanted Criminals",
        "https://punjabpolice.gov.in/",
        "IN", "Punjab Police wanted persons list."),
    src("kerala_police_wanted",
        "Kerala Police",
        "Wanted / Most Wanted Criminals",
        "https://keralapolice.gov.in/",
        "IN", "Kerala Police wanted persons list."),

    # ── International: financial regulators (East Asia / SE Asia) ───────────
    src("japan_fsa_administrative_actions",
        "Japan Financial Services Agency (JFSA)",
        "Administrative Actions Against Financial Institutions",
        "https://www.fsa.go.jp/en/news/index.html",
        "JP", "JFSA enforcement actions and orders."),
    src("japan_fsa_warnings_unregistered",
        "Japan Financial Services Agency (JFSA)",
        "Warnings on Unregistered Operators",
        "https://www.fsa.go.jp/en/ordinary/chuui/index.html",
        "JP", "JFSA warning list of unregistered crypto/securities operators."),
    src("south_korea_fss_sanctions",
        "Financial Supervisory Service (FSS) South Korea",
        "Sanctions and Disciplinary Actions",
        "https://english.fss.or.kr/",
        "KR", "FSS South Korea sanctions and disciplinary actions."),
    src("south_korea_fsc_press",
        "Financial Services Commission (FSC) South Korea",
        "Enforcement Actions Press Releases",
        "https://www.fsc.go.kr/eng/",
        "KR", "FSC South Korea press releases on enforcement actions."),
    src("bot_thailand_warning_list",
        "Bank of Thailand (BOT)",
        "Warning List on Unlicensed Operators",
        "https://www.bot.or.th/en/",
        "TH", "BOT Thailand warning list on unlicensed financial operators."),
    src("ojk_indonesia_blacklist",
        "Otoritas Jasa Keuangan (OJK) Indonesia",
        "Investment Alerts (Investasi Bodong)",
        "https://www.ojk.go.id/waspada-investasi",
        "ID", "OJK Indonesia investment alert blacklist."),
    src("sec_philippines_advisories",
        "Securities and Exchange Commission Philippines",
        "Advisories Against Unauthorized Entities",
        "https://www.sec.gov.ph/advisories/",
        "PH", "SEC Philippines advisories against unauthorized entities."),

    # ── International: Europe ───────────────────────────────────────────────
    src("bafin_germany_administrative_orders",
        "Bundesanstalt für Finanzdienstleistungsaufsicht (BaFin)",
        "Administrative Orders / Final Decisions",
        "https://www.bafin.de/EN/PublikationenDaten/Sanktionen/sanktionen_node_en.html",
        "DE", "BaFin sanctions / administrative orders catalogue."),
    src("dnb_netherlands_warnings",
        "De Nederlandsche Bank (DNB)",
        "Warnings on Unauthorized Activity",
        "https://www.dnb.nl/en/sector-information/warnings-from-dnb/",
        "NL", "DNB Netherlands warnings on unauthorised financial activity."),
    src("finma_switzerland_enforcement_orders",
        "FINMA Switzerland",
        "Enforcement Reports and Orders",
        "https://www.finma.ch/en/enforcement/",
        "CH", "FINMA enforcement reports and orders."),
    src("fca_uk_unauthorized_firms",
        "Financial Conduct Authority (FCA) United Kingdom",
        "Unauthorized Firms and Cloned Firms",
        "https://www.fca.org.uk/scamsmart/warning-list/",
        "GB", "FCA UK warning list of unauthorised and cloned firms."),
    src("central_bank_ireland_warnings",
        "Central Bank of Ireland",
        "Unauthorised Firms Warnings",
        "https://www.centralbank.ie/regulation/unauthorised-firms",
        "IE", "Central Bank of Ireland warnings on unauthorised firms."),
    src("central_bank_ireland_enforcement_actions",
        "Central Bank of Ireland",
        "Enforcement Actions and Settlement Agreements",
        "https://www.centralbank.ie/regulation/how-we-regulate/enforcement",
        "IE", "Central Bank of Ireland enforcement settlements and notices."),
    src("bank_of_spain_warnings",
        "Banco de España",
        "Warning List on Unauthorized Entities",
        "https://www.bde.es/wbe/en/",
        "ES", "Bank of Spain warning list on unauthorised entities."),
    src("consob_italy_administrative_orders",
        "CONSOB Italy",
        "Administrative Orders and Sanctions",
        "https://www.consob.it/web/consob-and-its-activities/sanctions",
        "IT", "CONSOB Italy administrative sanctions."),
    src("cmvm_portugal_warnings",
        "CMVM Portugal",
        "Warnings on Unauthorised Entities",
        "https://www.cmvm.pt/en/Pages/home.aspx",
        "PT", "CMVM Portugal warnings on unauthorised entities."),
    src("cnmv_spain_warnings",
        "Comisión Nacional del Mercado de Valores (CNMV) Spain",
        "Public Warnings on Unauthorised Entities",
        "https://www.cnmv.es/portal/Avisos/Avisos.aspx",
        "ES", "CNMV Spain warning list."),
    src("afm_netherlands_enforcement",
        "Authority for the Financial Markets (AFM) Netherlands",
        "Enforcement Measures",
        "https://www.afm.nl/en/sector/registers",
        "NL", "AFM Netherlands enforcement measures."),

    # ── International: Middle East / Africa / Americas ──────────────────────
    src("israel_isa_enforcement",
        "Israel Securities Authority (ISA)",
        "Enforcement Decisions",
        "https://www.isa.gov.il/sites/ISAEng/Pages/default.aspx",
        "IL", "ISA Israel enforcement decisions."),
    src("turkey_brsa_enforcement",
        "Banking Regulation and Supervision Agency (BRSA) Turkey",
        "Enforcement Decisions",
        "https://www.bddk.org.tr/Anasayfa/En",
        "TR", "BRSA Turkey enforcement decisions."),
    src("brazil_bacen_punicoes",
        "Banco Central do Brasil (BACEN)",
        "Punições Administrativas",
        "https://www.bcb.gov.br/en/financialstability",
        "BR", "BACEN Brazil administrative punishments register."),
    src("brazil_cvm_processos_sancionadores",
        "Comissão de Valores Mobiliários (CVM) Brazil",
        "Processos Administrativos Sancionadores",
        "https://www.gov.br/cvm/pt-br",
        "BR", "CVM Brazil administrative sanctioning processes."),
    src("south_korea_kofia_disciplinary",
        "Korea Financial Investment Association (KOFIA)",
        "Disciplinary Decisions",
        "https://eng.kofia.or.kr/",
        "KR", "KOFIA disciplinary decisions on member firms."),

    # ── International: multilateral debarments ──────────────────────────────
    src("world_bank_debarred_firms_individuals",
        "World Bank Group",
        "Debarred Firms and Individuals (Sanctions Board)",
        "https://www.worldbank.org/en/projects-operations/procurement/debarred-firms",
        "International", "World Bank Group debarred firms and individuals (sanctions)."),
    src("adb_debarred_firms_individuals",
        "Asian Development Bank (ADB)",
        "Sanctions List (Debarred Firms and Individuals)",
        "https://www.adb.org/site/integrity/sanctions",
        "International", "ADB sanctions list of debarred firms and individuals."),
    src("afdb_debarment_decisions",
        "African Development Bank (AfDB)",
        "Debarment Decisions",
        "https://www.afdb.org/en/topics-and-sectors/topics/anti-corruption",
        "International", "AfDB debarment decisions."),
    src("iadb_sanctioned_firms",
        "Inter-American Development Bank (IDB)",
        "Sanctioned Firms and Individuals",
        "https://www.iadb.org/en/transparency/sanctioned-firms-and-individuals",
        "International", "IDB list of sanctioned firms and individuals."),
    src("ebrd_ineligible_entities",
        "European Bank for Reconstruction and Development (EBRD)",
        "Ineligible Entities and Individuals",
        "https://www.ebrd.com/integrity-and-compliance.html",
        "International", "EBRD list of ineligible entities and individuals."),
    src("oecd_anti_bribery_enforcement",
        "Organisation for Economic Co-operation and Development (OECD)",
        "Foreign Bribery Convention Enforcement Tracker",
        "https://www.oecd.org/en/topics/policy-areas/anti-corruption-and-integrity-in-the-public-sector.html",
        "International", "OECD anti-bribery convention enforcement tracker."),

    # ── International: APAC additional ──────────────────────────────────────
    src("mas_singapore_prohibition_orders",
        "Monetary Authority of Singapore (MAS)",
        "Prohibition Orders",
        "https://www.mas.gov.sg/regulation/enforcement/enforcement-actions",
        "SG", "MAS Singapore prohibition orders against representatives."),
    src("asic_australia_banned_persons",
        "Australian Securities and Investments Commission (ASIC)",
        "Banned and Disqualified Persons",
        "https://asic.gov.au/online-services/search-asics-registers/banned-and-disqualified/",
        "AU", "ASIC Australia banned and disqualified persons register."),
    src("rbnz_new_zealand_enforcement",
        "Reserve Bank of New Zealand (RBNZ)",
        "Enforcement Actions",
        "https://www.rbnz.govt.nz/regulation-and-supervision/enforcement",
        "NZ", "RBNZ enforcement actions."),
    src("bnm_malaysia_administrative_actions",
        "Bank Negara Malaysia (BNM)",
        "Administrative Actions Against Regulated Entities",
        "https://www.bnm.gov.my/enforcement",
        "MY", "BNM administrative actions against regulated entities."),
    src("sebi_philippines_revoked_secondary_licenses",
        "Securities and Exchange Commission Philippines",
        "Revoked Secondary Licenses",
        "https://www.sec.gov.ph/",
        "PH", "SEC Philippines revoked secondary licenses register."),
]


def main():
    with open(SOURCES_JSON) as f:
        data = json.load(f)
    existing = {s["id"] for s in data["sources"]}
    added = []
    skipped = []
    for s in NEW:
        if s["id"] in existing:
            skipped.append(s["id"])
            continue
        data["sources"].append(s)
        existing.add(s["id"])
        added.append(s["id"])
    with open(SOURCES_JSON, "w") as f:
        json.dump(data, f, indent=2)
    print(f"Added {len(added)} new sources:")
    for sid in added:
        print(f"  + {sid}")
    if skipped:
        print(f"\nSkipped (already existed): {skipped}")
    print(f"\nTotal sources now: {len(data['sources'])}")


if __name__ == "__main__":
    main()
