#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# aws_migration.sh — package the Overwatch AML pipeline for AWS migration.
#
# What this script DOES (in order):
#   1. Verify AWS CLI is configured and resolve the account ID.
#   2. Create (if missing) a private, versioned S3 bucket:
#        overwatch-aml-backups-<account-id>-<region>
#   3. Upload the most recent pg_dump from /home/aayush/backups/.
#   4. Upload every per-source CSV in data/ (but NOT master_watchlist.csv —
#      that gets re-generated by combine.py).
#   5. Upload sources.json, scripts/, scrapers/, and the project's
#      requirements.txt as a single tarball.
#   6. Write a migration checklist to docs/aws_migration_checklist.txt.
#
# Things this script DOES NOT do (deliberate):
#   • Launch EC2 / RDS — you launch those in the console.
#   • Push .env or .claude/settings.local.json — secrets ride a separate channel.
#   • Restore the DB on the destination — see setup_aws_ec2.sh for that side.
#
# Usage:
#   ./scripts/aws_migration.sh                # uses AWS region from your CLI
#   AWS_REGION=ap-south-1 ./scripts/aws_migration.sh
#   DRY_RUN=1 ./scripts/aws_migration.sh      # show what would happen
# -----------------------------------------------------------------------------

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"
mkdir -p docs

DRY_RUN="${DRY_RUN:-0}"
REGION="${AWS_REGION:-${AWS_DEFAULT_REGION:-ap-south-1}}"   # Mumbai by default

say()  { printf '\033[1;36m[migr]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[err ]\033[0m %s\n' "$*" >&2; exit 1; }

# -----------------------------------------------------------------------------
# Step 0: sanity checks
# -----------------------------------------------------------------------------
command -v aws  >/dev/null 2>&1 || die "aws CLI not installed (sudo apt install awscli or use the bundled installer)"
command -v jq   >/dev/null 2>&1 || warn "jq not installed — output will be raw JSON"
command -v tar  >/dev/null 2>&1 || die "tar not found"
command -v gzip >/dev/null 2>&1 || die "gzip not found"

say "Verifying AWS credentials..."
if ! IDENT="$(aws sts get-caller-identity 2>&1)"; then
    die "aws sts get-caller-identity failed. Run 'aws configure' first.
            $IDENT"
fi
ACCOUNT_ID="$(echo "$IDENT" | jq -r .Account 2>/dev/null || echo "$IDENT" | grep -oE '[0-9]{12}' | head -1)"
[ -z "$ACCOUNT_ID" ] && die "Could not resolve AWS account id from sts output"
say "  account: $ACCOUNT_ID  region: $REGION"

BUCKET="overwatch-aml-backups-${ACCOUNT_ID}-${REGION}"
TS="$(date -u +%Y%m%dT%H%M%SZ)"
PREFIX="s3://${BUCKET}/migration-${TS}"

# -----------------------------------------------------------------------------
# Step 1: create / verify bucket (private + versioned + SSE-S3)
# -----------------------------------------------------------------------------
say "Creating/verifying S3 bucket: $BUCKET"
if [ "$DRY_RUN" = "1" ]; then
    say "  DRY-RUN: would aws s3api create-bucket / put-bucket-versioning / put-bucket-encryption"
else
    if aws s3api head-bucket --bucket "$BUCKET" 2>/dev/null; then
        say "  bucket exists already"
    else
        # us-east-1 doesn't accept LocationConstraint
        if [ "$REGION" = "us-east-1" ]; then
            aws s3api create-bucket --bucket "$BUCKET" >/dev/null
        else
            aws s3api create-bucket --bucket "$BUCKET" --region "$REGION" \
                --create-bucket-configuration "LocationConstraint=$REGION" >/dev/null
        fi
        aws s3api put-public-access-block --bucket "$BUCKET" \
            --public-access-block-configuration \
            "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true" >/dev/null
        aws s3api put-bucket-versioning --bucket "$BUCKET" \
            --versioning-configuration Status=Enabled >/dev/null
        aws s3api put-bucket-encryption --bucket "$BUCKET" \
            --server-side-encryption-configuration \
            '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}' >/dev/null
        say "  bucket created with versioning + SSE-S3 + public-access-block"
    fi
fi

# -----------------------------------------------------------------------------
# Step 2: upload latest pg_dump
# -----------------------------------------------------------------------------
DUMP="$(ls -t /home/aayush/backups/risk_pipeline_backup_*.dump 2>/dev/null | head -1 || true)"
if [ -z "$DUMP" ]; then
    warn "no pg_dump found in /home/aayush/backups/ — run pg_dump first or skip"
else
    say "Uploading pg_dump: $(basename "$DUMP") ($(du -h "$DUMP" | cut -f1))"
    if [ "$DRY_RUN" = "1" ]; then
        say "  DRY-RUN: would aws s3 cp '$DUMP' '$PREFIX/db/'"
    else
        aws s3 cp "$DUMP" "$PREFIX/db/" --storage-class STANDARD_IA \
            --metadata "source=overwatch-aml,kind=pg_dump,ts=$TS"
    fi
fi

# -----------------------------------------------------------------------------
# Step 3: upload per-source CSVs (excluding master)
# -----------------------------------------------------------------------------
say "Uploading per-source CSVs from data/ (excluding master_watchlist.csv)..."
CSV_TOTAL_BYTES=$(du -bc data/*.csv 2>/dev/null | tail -1 | cut -f1 || echo 0)
say "  total CSV size to upload: $((CSV_TOTAL_BYTES/1024/1024)) MB across $(ls data/*.csv 2>/dev/null | wc -l) files"
if [ "$DRY_RUN" = "1" ]; then
    say "  DRY-RUN: would aws s3 sync data/ '$PREFIX/data/' --exclude 'master_watchlist.csv' --exclude '*.pdf' --exclude '*.json'"
else
    aws s3 sync data/ "$PREFIX/data/" \
        --exclude "master_watchlist.csv" \
        --exclude "*.pdf" --exclude "*.json" \
        --exclude "backup/*" --exclude "snapshots/*"
fi

# -----------------------------------------------------------------------------
# Step 4: tarball of code + config
# -----------------------------------------------------------------------------
TARBALL="/tmp/overwatch-code-${TS}.tar.gz"
say "Building code tarball: $TARBALL"
tar --exclude='venv' --exclude='__pycache__' --exclude='.git' \
    --exclude='data/master_watchlist.csv' --exclude='logs/*.log' \
    --exclude='snapshots' --exclude='reports' --exclude='backups' \
    --exclude='.env' --exclude='.claude' \
    -czf "$TARBALL" \
    scripts/ scrapers/ utils/ configs/ recipes/ handlers/ engines/ \
    sources.json requirements.txt run_all.sh main.py classify.py \
    docs/ 2>/dev/null || true
say "  tarball size: $(du -h "$TARBALL" | cut -f1)"

if [ "$DRY_RUN" = "1" ]; then
    say "  DRY-RUN: would aws s3 cp '$TARBALL' '$PREFIX/code/'"
else
    aws s3 cp "$TARBALL" "$PREFIX/code/" \
        --metadata "source=overwatch-aml,kind=code,ts=$TS"
fi

# -----------------------------------------------------------------------------
# Step 5: write migration manifest + checklist
# -----------------------------------------------------------------------------
MANIFEST="docs/aws_migration_manifest_${TS}.json"
cat > "$MANIFEST" <<EOF
{
  "timestamp": "$TS",
  "account_id": "$ACCOUNT_ID",
  "region": "$REGION",
  "bucket": "$BUCKET",
  "prefix": "migration-${TS}",
  "artifacts": {
    "pg_dump": "$([ -n "$DUMP" ] && basename "$DUMP" || echo "none")",
    "code_tarball": "$(basename "$TARBALL")",
    "csv_count": $(ls data/*.csv 2>/dev/null | grep -v master_watchlist | wc -l),
    "csv_total_bytes": $CSV_TOTAL_BYTES
  },
  "next_steps": "Run scripts/setup_aws_ec2.sh on the destination EC2 instance"
}
EOF
say "Wrote manifest: $MANIFEST"

CHECKLIST="docs/aws_migration_checklist.txt"
cat > "$CHECKLIST" <<EOF
========================================================================
OVERWATCH AML — AWS MIGRATION CHECKLIST  (generated $TS)
========================================================================

Stage 1: AWS resources to provision in the console
   [ ] RDS PostgreSQL 15.x   db.t3.micro    Mumbai (ap-south-1)
        - Storage: 50 GB gp3
        - Master user: aayush
        - Initial db: risk_pipeline
        - Security group: inbound 5432 from EC2 SG only
   [ ] EC2 instance          t3.medium      Mumbai (ap-south-1)
        - AMI: Ubuntu 24.04 LTS
        - 30 GB gp3 root volume
        - Security group: inbound 22 from your IP only
        - IAM role: AmazonS3ReadOnlyAccess on $BUCKET (or scoped policy below)

Stage 2: After EC2 is up
   [ ] SSH in:  ssh -i ~/.ssh/<key>.pem ubuntu@<ec2-public-ip>
   [ ] Clone repo:  git clone <your-github-repo-url> risk-pipeline
   [ ] Run:  cd risk-pipeline && sudo ./scripts/setup_aws_ec2.sh
        - That script installs Python/PostgreSQL client, restores from S3,
          configures cron, and runs a validation.

Stage 3: Secrets (do not commit to repo)
   [ ] Copy .env  to EC2: scp .env ubuntu@<ec2>:~/risk-pipeline/.env
   [ ] Copy .claude/settings.local.json (Slack webhook) the same way

Stage 4: Verify
   [ ] psql to RDS:  PGPASSWORD=... psql -h <rds-endpoint> -U aayush risk_pipeline -c "SELECT COUNT(*) FROM watchlist_records;"
   [ ] Should see ~4.77M records (or whatever the dump contained)
   [ ] crontab -l should show 4 jobs (run_all, monitor, daily_pipeline, git_autopush)

Stage 5: Cut over
   [ ] Stop the local crontab on laptop:  crontab -r  (or comment out the 3 lines)
   [ ] First scheduled run on EC2: 06:00 IST tomorrow
   [ ] Watch logs/cron.log for the first day

S3 prefix containing this migration's artifacts:
   s3://$BUCKET/migration-${TS}/
EOF
say "Wrote checklist: $CHECKLIST"

# -----------------------------------------------------------------------------
say "============================================================"
say "DONE. Next: read $CHECKLIST and follow Stage 1 → Stage 5."
say "S3 prefix:  s3://$BUCKET/migration-${TS}/"
[ "$DRY_RUN" = "1" ] && say "(was a DRY RUN — re-run without DRY_RUN=1 to upload)"
say "============================================================"
